id = "pascal-ctags"
name = "Pascal Ctags LSP Support"
version = "0.1.1"
schema_version = 1
authors = ["Alex Niu <1847bell@gmail.com>"]
description = "Add Pascal ctags support to the Zed"
repository = "https://github.com/mazurel/zed-ctags"

[language_servers.pascal-ctags-lsp]
name = "Pascal Ctags LSP"
languages = ["C", "C++", "Python", "Pascal"]
